# NUMPY Tutorial

"""
what is numpy?

Numpy is a Python package, It stands for "Numerical Python". It is a Library consisting of multi-dimentional array objects and a collection of routines for processing of array.  

"""

In [1]:
import numpy

In [2]:
numpy.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [3]:
numpy.array([11,12,13,14,15])

array([11, 12, 13, 14, 15])

In [4]:
import numpy as np

In [5]:
a=np.array([90,92,93,88,55,76,12,35])

In [6]:
a

array([90, 92, 93, 88, 55, 76, 12, 35])

In [7]:
b=numpy.array([90,87,56,46,27,63])

In [8]:
b

array([90, 87, 56, 46, 27, 63])

In [9]:
a=np.array([1,2,3,4,5])

In [10]:
A 

NameError: name 'A' is not defined

In [11]:
a

array([1, 2, 3, 4, 5])

# Note:


Array are the continious memory location, which helps to keep all the data intact and can be searched easily easily.we can check shape,size,dimension of the elements inside.



In [12]:
a.size   # size will tell us number of elements inside the arrray

5

In [13]:
a.shape  #it will give us the number of dimension or 1 vector data in the array

(5,)

In [14]:
a.dtype

dtype('int32')

#### 2-dimensional data 

itconsist of rows and column
C=np.array([Row1[c1 ,c2],[c3,c4]row2])


In [15]:
# 2 dimension data
c=np.array([[1,2],[3,4]])

In [16]:
c

array([[1, 2],
       [3, 4]])

In [17]:
c.shape

(2, 2)

In [18]:
c.size

4

In [19]:
n=([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [20]:
n # without calling numpy array 

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [21]:
f=np.array(n) # seting new lib

In [22]:
f # calling array 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
f.shape # checking dimenssion

(4, 4)

In [24]:
f.size # checking shape (16 character)

16

In [25]:
f.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [26]:
f=np.array([[3,4,4],[4,5,6]])

In [27]:
f

array([[3, 4, 4],
       [4, 5, 6]])

In [28]:
f.min()

3

In [29]:
f.max()

6

In [30]:
f.base

In [31]:
f

array([[3, 4, 4],
       [4, 5, 6]])

In [32]:
f.itemsize #each elements consume 4 bytes 

4

In [33]:
f.dtype # IT WONT DEPEND ON THE COUNT,ITS TYPE

dtype('int32')

In [34]:
# bit to byte conversion 

""" Type is int 32(checking calculation) itemsize is 4 

8bit=1 byte

HERE 32 IS 32 BIT

32/8bit

Each element consums 4 byte. 

"""

' Type is int 32(checking calculation) itemsize is 4 \n\n8bit=1 byte\n\n32/8bit\n\nEach element consums 4 byte. \n\n'

In [35]:
# data will give us the memory location

f.data

In [36]:
f=np.arange(5)

In [37]:
f

array([0, 1, 2, 3, 4])

In [38]:
x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [39]:
x.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
x=np.array([1,2,3,4,5,6,7,8],dtype=float)

In [41]:
x

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [42]:
x.reshape(4,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [43]:
x.itemsize

8

In [44]:
x.size


8

In [45]:
x.shape

(8,)

In [47]:
x.dtype

dtype('float64')

In [50]:
a.ndim #gives dimension

1

In [51]:
a=np.array([[1,2,3],[4,6,5],[9,8,7],[11,13,14]])

In [52]:
a

array([[ 1,  2,  3],
       [ 4,  6,  5],
       [ 9,  8,  7],
       [11, 13, 14]])

In [53]:
a.ndim

2

In [54]:
a.size

12

In [55]:
a.shape#(4 is row and 3 is column)

(4, 3)

In [57]:
x=np.arange(25)

In [58]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [59]:
a=x.reshape(5,5)

In [60]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
a=np.arange(30,60,dtype=float)

In [65]:
a

array([30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
       43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
       56., 57., 58., 59.])

In [68]:
m=a.reshape(3,10)

In [69]:
m

array([[30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.]])

In [70]:
a=np.arange(40).reshape(4,10)

In [71]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [72]:
a.ndim

2

In [73]:
a.size

40

In [74]:
a.shape

(4, 10)

In [76]:
a.data

In [77]:
a.dtype

dtype('int32')

In [78]:
a.itemsize

4

In [79]:
type(a)

numpy.ndarray

### RAVAL OPERATION:

" IT WOULD CONVERT NUMPY ARRAY OPERATION TO SINGLE LINE OR SINGLE NUMPY ARRAY "



In [81]:
ra=np.array([[34,78,89],[22,33,77]])

In [82]:
ra # np.array

array([[34, 78, 89],
       [22, 33, 77]])

In [84]:
print(ra.ravel()) # gets converted to one line statement.

[34 78 89 22 33 77]


In [85]:
import numpy as np

In [88]:
b=np.array([[1,2,3],[5,6,4]]).reshape(3,2)

In [89]:
b

array([[1, 2],
       [3, 5],
       [6, 4]])

In [90]:
c=b.ravel()

In [91]:
c

array([1, 2, 3, 5, 6, 4])

In [93]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [97]:
np.arange(15) #arange function 0 to 14 generated  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
np.arange(5,15) # start,stop

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [99]:
np.arange(5,15,2) #start/stop/jump

array([ 5,  7,  9, 11, 13])

In [1]:
import numpy

In [2]:
a=numpy.array([1,12,13,14,15,16])

In [3]:
a

array([ 1, 12, 13, 14, 15, 16])

In [4]:
a.shape

(6,)

In [5]:
a.size

6

In [6]:
a.dtype

dtype('int32')

In [7]:
a.itemsize

4

In [8]:
a.data

In [11]:
c=a.reshape(2,3)

In [10]:
a.ndim

1

In [12]:
c

array([[ 1, 12, 13],
       [14, 15, 16]])

In [13]:
c.ndim

2

In [15]:
a=numpy.arange(30)

In [16]:
c

array([[ 1, 12, 13],
       [14, 15, 16]])

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
c=a.reshape(3,10)

In [19]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
c.max()

29

In [23]:
c.min()

0

In [30]:
a=numpy.zeros([4,4])

In [31]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
a.ravel()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
m=numpy.ones([4,5])

In [35]:
m

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
m.reshape(2,10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
m.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

### BROADCASTING IN NUMPY

In [38]:
import numpy as np

In [39]:
i=np.array([1,2,3])
u=np.array([1,2,3])
i*u  # here all in brackets, hence mutiply would be 1*1=1,2*2=2,3*3=3

array([1, 4, 9])

In [42]:
a=np.array([1,2,3],dtype=float)
b=2
a*b # here 2 mutiply with a 2*1.0,2*2.0,3*3.0


array([2., 4., 6.])

In [43]:
a=np.array([10])

In [44]:
a

array([10])

In [47]:
a=np.arange(10)

In [55]:
b=np.arange(0,2)

In [56]:
a*b

ValueError: operands could not be broadcast together with shapes (10,) (2,) 

In [57]:
newb=1

In [59]:
a*newb # newb holds 1, one gets multiplies with 0 to 9 in a data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
newb**2

1

# Random Function

In [63]:
b=np.random.random([2,3]) #will generate any number

In [64]:
b 

array([[0.96314375, 0.44769308, 0.88091634],
       [0.20512696, 0.07186864, 0.16471203]])

In [66]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [68]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
c=np.ones([4,4])

In [70]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
d=np.ones([4,4])

In [73]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
e=c+d

In [75]:
e

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

## Universal function:

In [76]:
e.expo

AttributeError: 'numpy.ndarray' object has no attribute 'expo'

In [80]:
bi=np.arange(3)

In [81]:
bi

array([0, 1, 2])

In [82]:
np.exp(bi)

array([1.        , 2.71828183, 7.3890561 ])

In [85]:
ex=np.array([6,7,8])

In [86]:
np.exp(ex)

array([ 403.42879349, 1096.63315843, 2980.95798704])

In [87]:
6**6

46656

In [98]:
np.sqrt(bi)

array([0.        , 1.        , 1.41421356])

In [99]:
c=np.array([1,2,3,4,5,6])

np.sqrt(c)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [101]:
np.square(c)

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [102]:
np.add(c,bi)

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [103]:
d=np.array([6,7,8,9,10,11])

In [104]:
c*d

array([ 6, 14, 24, 36, 50, 66])

In [105]:
np.add(c,d)

array([ 7,  9, 11, 13, 15, 17])

In [106]:
c

array([1, 2, 3, 4, 5, 6])

In [107]:
d

array([ 6,  7,  8,  9, 10, 11])

In [108]:
np.multiply(c,d)

array([ 6, 14, 24, 36, 50, 66])

# index,Slicing,Iterating:

In [109]:
a=np.arange(10)

In [110]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
a[0]

0

In [112]:
a[4]

4

In [114]:
a[2:5]

array([2, 3, 4])

In [115]:
a[-1]

9

In [117]:
a[-5:-1]

array([5, 6, 7, 8])

In [118]:
# if marks are missing we will write np.nan

marks=np.array([np.nan,1,2,3,5,np.nan,np.nan,8,9,np.nan])

In [119]:
marks.reshape(2,5)

array([[nan,  1.,  2.,  3.,  5.],
       [nan, nan,  8.,  9., nan]])

In [121]:
# Uniform distribution of data:

np.random.rand(4,4) # will generate postive and uniform data

array([[0.19640301, 0.77080249, 0.38335109, 0.29474087],
       [0.1500546 , 0.73460489, 0.14820979, 0.67687362],
       [0.44748281, 0.58848686, 0.66140777, 0.99865615],
       [0.61351628, 0.34423945, 0.14575742, 0.31907292]])

In [122]:
# will generate sum positive, negative

np.random.randn(4,4)

array([[ 1.0775921 ,  0.39541198,  0.03407509,  1.11426998],
       [ 0.52840746, -0.44109162, -0.78977195,  1.11295629],
       [-0.51110268,  2.11170045,  1.39091673, -1.49910612],
       [ 0.31521272,  0.00718371, -0.34740666, -0.97746617]])

------------------------------------