# Numpy Tutorial

Numpy stands for numerical Python

In [1]:
import numpy as np

In [ ]:
# array- continious memory

In [2]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [4]:
np.array([11,12,1,3,14,15])

array([11, 12,  1,  3, 14, 15])

In [6]:
#holding in var
a=np.array([10,11,12,13,14,15])

In [7]:
a

array([10, 11, 12, 13, 14, 15])

In [8]:
b=np.array([90,20,303,45,67,98])
b

array([ 90,  20, 303,  45,  67,  98])

In [9]:
#number of element
b.size

6

In [10]:
a.shape

(6,)

# rows and columns

In [16]:
c=np.array([[1,2],[3,4]])#row1,row2
c

array([[1, 2],
       [3, 4]])

In [17]:
c.shape

(2, 2)

In [18]:
d=np.array([[29,3],[45,6],[98,56]])
d

array([[29,  3],
       [45,  6],
       [98, 56]])

In [19]:
d.shape

(3, 2)

In [20]:
f=np.array([[1,2,3,4],[5,6,7,8]])

In [21]:
f

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
f.shape

(2, 4)

In [23]:
j=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
j

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
j.shape

(4, 3)

In [29]:
np.ndim(j)

2

In [31]:
j.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
j.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [33]:
j.min()

1

In [34]:
j.max()

12

In [37]:
a.dtype # int32 shows 32 bits are consumed (shows bits alocated)

dtype('int32')

In [36]:
a.itemsize # storage has 4 bit (32bit/8bit)=4bit

4

In [38]:
f=np.array([[1,2,3,4],[5,6,7,8]],dtype='float64')

In [39]:
f

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [41]:
f.dtype 

dtype('float64')

In [42]:
f.itemsize #64/8 =8 bit consume

8

In [46]:
x=np.arange(10)
print(x)
len(x)

[0 1 2 3 4 5 6 7 8 9]


10

In [47]:
a=x.reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
c=np.arange(15)
c.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
z=np.arange(20)
a=z.reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [52]:
z.ndim

1

In [53]:
a.ndim

2

In [54]:
a.itemsize

4

In [55]:
a.dtype

dtype('int32')

In [56]:
z.itemsize

4

In [57]:
z.dtype

dtype('int32')

In [59]:

a=np.array([1,2,3,4,5,66,7,8,9,10])
s=a.reshape(2,5)
s

array([[ 1,  2,  3,  4,  5],
       [66,  7,  8,  9, 10]])

In [61]:
s.dtype

dtype('int32')

In [62]:
s.itemsize

4

In [63]:
s.shape

(2, 5)

In [64]:
s.ndim

2

In [65]:
# back to one line
s.ravel()

array([ 1,  2,  3,  4,  5, 66,  7,  8,  9, 10])

In [66]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [69]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [72]:
np.arange(1,5)

array([1, 2, 3, 4])

In [74]:
np.arange(0,5,2)

array([0, 2, 4])

In [76]:
e=np.arange(5,50,5)
c=e.reshape(3,3)

In [77]:
c

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# Broadcasting

In [78]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
#1*1,2*2... so on
a*b

array([ 1,  4,  9, 16, 25])

In [79]:
a=np.array([1.2,2.3,1,2])
a*2

array([2.4, 4.6, 2. , 4. ])

In [80]:
a=np.array([20,30,40,50])
b=np.arange(4) #0,1,2,3
a*b

array([  0,  30,  80, 150])

In [81]:
a-b

array([20, 29, 38, 47])

In [83]:
a*b

array([  0,  30,  80, 150])

In [86]:
a**b

array([     1,     30,   1600, 125000], dtype=int32)

In [89]:
c=np.ones([2,3])
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [90]:
c=np.random.random([2,3])
c

array([[0.94186603, 0.73775516, 0.2303168 ],
       [0.99520251, 0.60358573, 0.44021515]])

In [97]:
cb=np.ones([2,3])
cb

array([[1., 1., 1.],
       [1., 1., 1.]])

In [98]:
c+cb

array([[1.94186603, 1.73775516, 1.2303168 ],
       [1.99520251, 1.60358573, 1.44021515]])

In [99]:
c-cb

array([[-0.05813397, -0.26224484, -0.7696832 ],
       [-0.00479749, -0.39641427, -0.55978485]])

In [100]:
c*cb

array([[0.94186603, 0.73775516, 0.2303168 ],
       [0.99520251, 0.60358573, 0.44021515]])

# slicing

In [102]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a[2]

2

In [106]:
a[:2]

array([0, 1])

In [107]:
a.reshape([2,5])


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
d3=np.array([np.nan,1,2,3,np.nan,6,7,np.nan])

In [109]:
d3

array([nan,  1.,  2.,  3., nan,  6.,  7., nan])

In [112]:
d3.reshape([2,4])

array([[nan,  1.,  2.,  3.],
       [nan,  6.,  7., nan]])

In [113]:
d3.dtype

dtype('float64')

In [115]:
d3.itemsize

8

In [116]:
d3.ndim

1

In [117]:
d3.ravel()

array([nan,  1.,  2.,  3., nan,  6.,  7., nan])

In [120]:
np.random.rand(2,2)

array([[0.87903289, 0.91922256],
       [0.15196776, 0.89905863]])

In [122]:
np.random.randn(2,2) # some postive and some negative

array([[ 0.44776945, -0.24821564],
       [ 1.38982899,  0.60998259]])

# More LMS practice

In [1]:
import numpy as np

np.array([5,8,9])# structure in numpy 
#array hold only numerical

array([5, 8, 9])

In [2]:
type([5,8,9])

list

In [3]:
type(np.array([5,8,9]))

numpy.ndarray

In [4]:
a=np.array([[1,2],[3,4],[4,5]])
print("Type -",a.dtype)

Type - int32


In [5]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [6]:
a.ndim

2

In [7]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 4, 5]])

In [8]:
a.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
c=np.array([1,2,3],dtype=float)
c

array([1., 2., 3.])

In [11]:
c.dtype

dtype('float64')

In [12]:
c.itemsize

8

In [13]:
# creating Matrix
np.array(np.mat('1 2 3;3 2 1'))

array([[1, 2, 3],
       [3, 2, 1]])

In [15]:
#convert a list into an array:

a=[1,2]

#  Making copy of a
c=np.array(a)
print(c)

[1, 2]


# Numpy Data Types

In [16]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

mat= np.array(my_mat)

print("Type/class of this object: ",type(mat))
print("Here is the matrix\n...........\n",mat,"\n------")
print("Dimension shows ",mat.ndim,sep='')#sep is another option
print("Size of the matrix ",mat.size)
print("Shape of the matrix ",mat.shape)
print("Data type of the matrix ",mat.dtype)
print("Item Size ",mat.itemsize)

Type/class of this object:  <class 'numpy.ndarray'>
Here is the matrix
...........
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
------
Dimension shows 2
Size of the matrix  9
Shape of the matrix  (3, 3)
Data type of the matrix  int32
Item Size  4


# Arrange and Linspace

In [17]:
# range- python
# aranage for numpy

In [23]:
a=np.arange(2,10.5,0.4)
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [25]:
# step size is reversed
a[::-1] #[start:endpoint:stepsize]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [24]:
# count till 10 from back "0 to 9"
a[:10:-1] #[start:endpoint:stepsize]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4])

In [26]:
print("Every 5th number from 50 in reverse order \n",np.arange(50,0,-5))

Every 5th number from 50 in reverse order 
 [50 45 40 35 30 25 20 15 10  5]


# Lin space

np.linsapce(0,40,10)

- would generate linear space between 0 to 40  and ount will be 10 

In [28]:
# get me 10 numbers having linear space between them like 0 to 40 
print("Linear spaced number between 0 to 40 \n\n------- ")
print(np.linspace(0,40,10))

Linear spaced number between 0 to 40 

------- 
[ 0.          4.44444444  8.88888889 13.33333333 17.77777778 22.22222222
 26.66666667 31.11111111 35.55555556 40.        ]


In [30]:
# Include end point (will add the last number) and retsep(will show stop taken)
np.linspace(2.0,3.0,num=4,endpoint=False,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

In [31]:
np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

# Matrix Creation

In [32]:
print("Vector of zeroes\n------------------------")
print(np.zeros(5))

Vector of zeroes
------------------------
[0. 0. 0. 0. 0.]


In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
# for one we use bracket (for list)
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# contruct diagonal matrix

x= np.arange(30).reshape(3,10)

In [41]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Random Number Generation

In [42]:
import numpy as np

# number genration

1. np.random.rand-> positive number with normal distribution
2. np.random.randn-> postive and negative number generated 
3. np.random.randint-> to genrate postive postive number


### NOTE:(Seeding)

- As seeding remains same the number rotation will be same
- No seeding will give different different numbers

### (Rand) Uniform Distribution

- Will show the uniform distribution

In [43]:
np.random.seed(5)# seeding will generate same number
print("Random number generate (from uniform distribution)")
print(np.random.rand(10,6))

Random number generate (from uniform distribution)
[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703 0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292  0.26581912 0.28468588 0.25358821]
 [0.32756395 0.1441643  0.16561286 0.96393053 0.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309 0.57766286]
 [0.00164217 0.51547261 0.63979518 0.9856244  0.2590976  0.80249689]
 [0.87048309 0.92274961 0.00221421 0.46948837 0.98146874 0.3989448 ]
 [0.81373248 0.5464565  0.77085409 0.48493107 0.02911156 0.08652569]
 [0.11145381 0.25124511 0.96491529 0.63176605 0.8166602  0.566082  ]]


In [44]:
np.random.seed(5)# seeding will generate same number
print("Random number generate (from uniform distribution)")
print(np.random.rand(10,6))

Random number generate (from uniform distribution)
[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005  0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703 0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292  0.26581912 0.28468588 0.25358821]
 [0.32756395 0.1441643  0.16561286 0.96393053 0.96022672 0.18841466]
 [0.02430656 0.20455555 0.69984361 0.77951459 0.02293309 0.57766286]
 [0.00164217 0.51547261 0.63979518 0.9856244  0.2590976  0.80249689]
 [0.87048309 0.92274961 0.00221421 0.46948837 0.98146874 0.3989448 ]
 [0.81373248 0.5464565  0.77085409 0.48493107 0.02911156 0.08652569]
 [0.11145381 0.25124511 0.96491529 0.63176605 0.8166602  0.566082  ]]



### (Randn) Mean is 0 and STD is standard normal

### Postive and negative Generation

In [46]:
print("Number from Normal distribution with zero mean and standard deviation 1 i.e standard normal")
print(np.random.randn(10,3))

Number from Normal distribution with zero mean and standard deviation 1 i.e standard normal
[[ 1.13934298  0.4944404  -0.33633626]
 [-0.10061435  1.41339802  0.22125412]
 [-1.31077313 -0.68956523 -0.57751323]
 [ 1.15220477 -0.10716398  2.26010677]
 [ 0.65661947  0.12480683 -0.43570392]
 [ 0.97217931 -0.24071114 -0.82412345]
 [ 0.56813272  0.01275832  1.18906073]
 [-0.07359332 -2.85968797  0.7893664 ]
 [-1.87774088  1.53875615  1.82136474]
 [-0.42703139 -1.16470191 -1.39707402]]


#### Here the number lies between mean 0 and standard deviation 1

In [47]:
# randint(Low,high, no of size to be drawn )
print("Random integer vector: ",np.random.randint(5,20,10))

Random integer vector:  [18 12  6 12  7 11  8 11 13  5]


In [48]:
print("\nRandom integer matrix low, high, and matrix shape")
print(np.random.randint(1,30,(6,7)))


Random integer matrix low, high, and matrix shape
[[14 10  2 10  1  9 24]
 [ 8 26  5 16 18 28  5]
 [19  2 24  6 29  5 19]
 [ 3 14  2 19  4  2 19]
 [21 10  1 18  3 15 20]
 [ 9 11  6 27 16 22 21]]


# by own:

In [71]:
np.random.rand(3,4)

array([[0.51288995, 0.53182487, 0.89533366, 0.07107016],
       [0.34445056, 0.15688357, 0.70314955, 0.86458372],
       [0.52913005, 0.52633773, 0.3215009 , 0.48665962]])

In [64]:
np.random.randn(3,5)

array([[ 1.12890829, -0.96246288,  0.06194162, -1.04606453, -0.94774627],
       [-0.03111909,  0.48279349,  0.2791851 , -0.13685186,  1.43637393],
       [-0.2948763 ,  0.89485343,  1.29403677,  0.67470281,  0.57764607]])

In [67]:
# generated 5 number
np.random.randint(3,14,5)

array([ 4, 12, 12,  5,  3])

In [68]:
# generated 2,5 matrix
np.random.randint(3,5,(3,4))

array([[3, 4, 4, 4],
       [3, 4, 3, 3],
       [4, 3, 3, 4]])

# Numpy Condition

In [72]:
a=np.random.randint(1,40,10)
a

array([ 1,  1,  7, 27,  5, 18, 13, 32, 37, 35])

In [73]:
# replace data with fixed numbers

np.clip(a,a_min=10,a_max=25)

# any number less than 25 make it 10, more than 25 make it 25

array([10, 10, 10, 25, 10, 18, 13, 25, 25, 25])

In [74]:
# It gives index details
print(np.where(a<10))

(array([0, 1, 2, 4], dtype=int64),)


In [75]:
# find if data exists in the array
print(np.where(a==38))

(array([], dtype=int64),)


# Reshape

In [76]:
import numpy as np
from numpy.random import randint as ri

a=ri(1,99,30)
a

array([62, 95, 92, 76, 63, 52,  3, 97, 20,  8, 77, 67, 57,  1, 58, 32, 87,
       75, 38, 65, 52, 13, 60, 26, 40, 34, 25,  8, 69, 82])

In [84]:
# 2 matrix (3,5)=15
b=a.reshape(2,3,5)
b

array([[[62, 95, 92, 76, 63],
        [52,  3, 97, 20,  8],
        [77, 67, 57,  1, 58]],

       [[32, 87, 75, 38, 65],
        [52, 13, 60, 26, 40],
        [34, 25,  8, 69, 82]]])

In [78]:
c=a.reshape(6,5)
c

array([[62, 95, 92, 76, 63],
       [52,  3, 97, 20,  8],
       [77, 67, 57,  1, 58],
       [32, 87, 75, 38, 65],
       [52, 13, 60, 26, 40],
       [34, 25,  8, 69, 82]])

In [86]:
print("Min of a : ",c.min())
print("Max of a  : ",c.max())

Min of a :  1
Max of a  :  97


# Sorting

In [87]:
M=ri(1,100,25).reshape(5,5)
M


array([[70, 70, 82, 21, 87],
       [ 2, 75, 71, 49, 56],
       [52, 98, 40,  1, 31],
       [43, 88, 72,  5, 63],
       [26, 18, 51, 64, 18]])

In [90]:
#default sort by rows (axis=1)
print("Here is the sorted matrix along each row\n",np.sort(M))# row wise

Here is the sorted matrix along each row
 [[21 70 70 82 87]
 [ 2 49 56 71 75]
 [ 1 31 40 52 98]
 [ 5 43 63 72 88]
 [18 18 26 51 64]]


In [93]:
print("Here sort by each column\n\n",np.sort(M,axis=0))

Here sort by each column

 [[ 2 18 40  1 18]
 [26 70 51  5 31]
 [43 75 71 21 56]
 [52 88 72 49 63]
 [70 98 82 64 87]]


# Indexing and slicing

In [94]:
arr= np.arange(13,30)
print("Array: ",arr)

Array:  [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [96]:
print("Element  at 7th index is ",arr[7])

Element  at 7th index is  20


In [97]:
arr=np.arange(0,21,2)

In [98]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [99]:
#pass the index number in list
arr[[2,4,9]]

array([ 4,  8, 18])

In [105]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
print("\nDouble Bracket is indexing--------------------")
print("Element in the row index 1 and column index 2: ",mat[1][2])
#row 1 and column=2


Double Bracket is indexing--------------------
Element in the row index 1 and column index 2:  6


In [107]:
print("Entire row at index 2: ",mat[2])

Entire row at index 2:  [7 8 9]


In [108]:
print("Element in row index 1 and column index 2: ",mat[:,1:])#row,column
# select all rows and column 1 to all

Element in row index 1 and column index 2:  [[2 3]
 [5 6]
 [8 9]]


In [113]:
mat[[2,1]]

array([[7, 8, 9],
       [4, 5, 6]])

In [116]:
mat[0:2,[1,2]]

array([[2, 3],
       [5, 6]])

In [117]:
print("Original Index",mat)

Original Index [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Update

In [118]:
mat[0,1]=35
print(mat)

[[ 1 35  3]
 [ 4  5  6]
 [ 7  8  9]]


In [119]:
mat[1,0]=36
mat

array([[ 1, 35,  3],
       [36,  5,  6],
       [ 7,  8,  9]])

# Subseting

In [120]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit number\n-----------------\n",mat)

Matrix of random 2-digit number
-----------------
 [[83 11 32 43 37]
 [92 39 12 72 65]
 [20 63 98 64 19]]


In [122]:
# would show true and false
[mat>70]

[array([[ True, False, False, False, False],
        [ True, False, False,  True, False],
        [False, False,  True, False, False]])]

In [121]:
# show me where marks is greater than 70
xyz=mat[mat>70]
xyz

array([83, 92, 72, 98])

In [123]:
print("elements greater than 50 \n",mat[mat>50])

elements greater than 50 
 [83 92 72 65 63 98 64]


In [125]:
# check if any digit is having 50

print(np.where(mat==50))

(array([], dtype=int64), array([], dtype=int64))


In [126]:
#Shows No row,column index have 50

# next
print(np.where(mat==83))

(array([0], dtype=int64), array([0], dtype=int64))


In [127]:
#shows row is 0 and column is zero

# lets check
mat

array([[83, 11, 32, 43, 37],
       [92, 39, 12, 72, 65],
       [20, 63, 98, 64, 19]])

#  Universal Functions

In [129]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

In [130]:
print("\n 1st Matrix of Random Single Digit numbers\n\n",mat1)
print("\n 2nd Matrix of Random Single Digit numbers\n\n",mat2)


 1st Matrix of Random Single Digit numbers

 [[1 8 2]
 [1 3 2]
 [9 6 2]]

 2nd Matrix of Random Single Digit numbers

 [[5 1 3]
 [7 1 4]
 [3 6 7]]


In [131]:
print("\n Addition\n-----------------\n",mat1+mat2)

#5+1=6 and so on


 Addition
-----------------
 [[ 6  9  5]
 [ 8  4  6]
 [12 12  9]]


In [132]:
print("\n Multiplication\n---------------\n",mat1*mat2)


 Multiplication
---------------
 [[ 5  8  6]
 [ 7  3  8]
 [27 36 14]]


In [134]:
print("MAT1\n   \n",mat1)
print("MAT2\n",mat2)

MAT1
   
 [[1 8 2]
 [1 3 2]
 [9 6 2]]
MAT2

 [[5 1 3]
 [7 1 4]
 [3 6 7]]


In [135]:
print("\n Division\n-----------------------\n",mat1/mat2)

print("\nLinear Combination :",3*mat1-2*mat2)


 Division
-----------------------
 [[0.2        8.         0.66666667]
 [0.14285714 3.         0.5       ]
 [3.         1.         0.28571429]]

Linear Combination : [[ -7  22   0]
 [-11   7  -2]
 [ 21   6  -8]]


# Broad casting

In [141]:
start=np.zeros([3,3])
print("Zero Matrix\n\n",start)

Zero Matrix

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [157]:
add_rows=np.ones((3,3))
add_rows

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [159]:
add_rows=np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [153]:
s=np.array([1,3,2],dtype=int)

In [164]:
print("Zeros\n\n",start,"\n")
# would add row wise
print("row\n\n",add_rows)

Zeros

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

row

 [[1 0 2]]


In [160]:
# index0 with all index 0,1,2(column-1)
# index1 with all index 0,1,2(column-2)
# index2 with all index 0,1,2(column-3)
# row wise
y=start+add_rows
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [166]:
column=add_rows.T
column

In [170]:
# add column wise
su= column+start

In [171]:
su

array([[1., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.]])

# Array Math

In [174]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

In [176]:
print("Matrix for random Single Digit Number\n-----------\n",mat1)
print("Matrix of random Single DIgit Number\n-------------\n",mat2)

Matrix for random Single Digit Number
-----------
 [[2 2 6]
 [5 7 6]
 [7 1 2]]
Matrix of random Single DIgit Number
-------------
 [[6 4 4]
 [3 1 7]
 [7 2 3]]


In [177]:
print("\n Square Root of 1st Matrix using\n--------------------------------\n",np.sqrt(mat1))
print("\n Square of 1st Matrix using\n-------------------------------------\n",np.square(mat1))


 Square Root of 1st Matrix using
--------------------------------
 [[1.41421356 1.41421356 2.44948974]
 [2.23606798 2.64575131 2.44948974]
 [2.64575131 1.         1.41421356]]

 Square of 1st Matrix using
-------------------------------------
 [[ 4  4 36]
 [25 49 36]
 [49  1  4]]


# All function all Listed here, call them as per requirement

In [178]:
import numpy as np
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

# Math Function

In [179]:
import math
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']
