# Data Structure Nulls

In [1]:
import numpy as np
import pandas as pd

In [5]:
ser=pd.Series([1])
ser

0    1
dtype: int64

# Series 

- Capital S, 1 column


# DataFrame

- capital D and F capital
- more than 1 column



In [6]:
#  #  notice dtype
ser=pd.Series([20,15.5,'10'])
ser

0      20
1    15.5
2      10
dtype: object

In [7]:
type(ser)

pandas.core.series.Series

In [8]:
# create Dictionary
dict={'A':[1,2,3],'B':[5,8,9],'C':[1,2,3]}
dict

{'A': [1, 2, 3], 'B': [5, 8, 9], 'C': [1, 2, 3]}

In [9]:
df=pd.DataFrame(dict)
df

A  B  C
0  1  5  1
1  2  8  2
2  3  9  3

In [14]:
# will add new values into it

df['State']='CA,NV,AZ'.split(",")
df['State']

0    CA
1    NV
2    AZ
Name: State, dtype: object

In [11]:
df

A  B  C State
0  1  5  1    CA
1  2  8  2    NV
2  3  9  3    AZ

In [15]:
dict={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [16]:
dict

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [17]:
df=pd.DataFrame(dict)

In [18]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [19]:
df['D']=[20,30,40]
df

A    B  C   D
0  1.0  5.0  1  20
1  2.0  NaN  2  30
2  NaN  NaN  3  40

### Dropping Row or column of all missing Values

In [21]:
print("\n Dropping any column with  Nan values\n ",'-'*35,sep=' ')
print(df.dropna(axis=1))


 Dropping any column with  Nan values
  -----------------------------------
   C   D
0  1  20
1  2  30
2  3  40


In [25]:
# if we will not save the same result will remain same.

print(df.dropna(axis=0)) # check the deletion as per rows

     A    B  C   D
0  1.0  5.0  1  20


#  Fill Na

-  filling of Data

In [27]:
print("\n Filling Values with a default values \n",'-'*35,sep=' ')
print(df.fillna(value=50))


 Filling Values with a default values 
 -----------------------------------
      A     B  C   D
0   1.0   5.0  1  20
1   2.0  50.0  2  30
2  50.0  50.0  3  40


In [30]:
print("\nFilling values with a computed values(mean of column A here)\n",'-'*60,sep=' ')
print(df.fillna(value=df['C'].mean(),inplace=True))


Filling values with a computed values(mean of column A here)
 ------------------------------------------------------------
None


#  Note:
Inplace will save the data set.

In [31]:
# create data frame

data={'company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
     'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
     'Sales':[200,120,340,124,243,350]}

df=pd.DataFrame(data)
df

company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [34]:
byComp=df.groupby('company')
print("\nGrouping by 'Company' column and listing mean Sales\n",'-'*50)
byComp.mean()


Grouping by 'Company' column and listing mean Sales
 --------------------------------------------------


Sales
company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [36]:
print("\nGrouping by 'Comapany' column and listing sum of sales\n",'-'*50,sep=' ')
print(byComp.sum())


Grouping by 'Comapany' column and listing sum of sales
 --------------------------------------------------
         Sales
company       
FB         593
GOOG       320
MSFT       464


# Concate Data Frame

In [37]:
df1=pd.DataFrame(data={'Mat':[40,67,55,45],
                      'Eng':[56,87,34,56],
                      'Sci':[34,56,78,89],
                      'Chem':[45,67,89,89]},index=['Ravi','Syam','Rafad','Abhi'])

In [38]:
df1

Mat  Eng  Sci  Chem
Ravi    40   56   34    45
Syam    67   87   56    67
Rafad   55   34   78    89
Abhi    45   56   89    89

In [39]:
df2=pd.DataFrame(data={'Mat':[50,77,97,69],
                      'Eng':[66,87,34,66],
                      'Sci':[81,87,69,71],
                      'Chem':[56,79,12,34]},index=['Shaan','Mahi','Viru','Mona'])
df2

Mat  Eng  Sci  Chem
Shaan   50   66   81    56
Mahi    77   87   87    79
Viru    97   34   69    12
Mona    69   66   71    34

In [41]:
df3=pd.DataFrame({'Mat':[67,89,98,56],
                'Eng':[56,87,89,71],
                'Sci':[56,67,56,87],
                'Chem':[34,56,56,87]},index=['Astha','Rohit','Rahul','Shital']
               )
df3

Mat  Eng  Sci  Chem
Astha    67   56   56    34
Rohit    89   87   67    56
Rahul    98   89   56    56
Shital   56   71   87    87

### Concate

In [45]:
df_cat1=pd.concat([df1,df2,df3],axis=0)
print("\n After conactenation along row\n",'-'*30,sep=" ")
print(df_cat1)

#df1
#df2
#df3


 After conactenation along row
 ------------------------------
        Mat  Eng  Sci  Chem
Ravi     40   56   34    45
Syam     67   87   56    67
Rafad    55   34   78    89
Abhi     45   56   89    89
Shaan    50   66   81    56
Mahi     77   87   87    79
Viru     97   34   69    12
Mona     69   66   71    34
Astha    67   56   56    34
Rohit    89   87   67    56
Rahul    98   89   56    56
Shital   56   71   87    87


In [48]:
df_concat2=pd.concat([df1,df2,df3],axis=1)
print("\n Conacte as per columns\n","-"*30 ,sep=" ")
print(df_concat2)


 Conacte as per columns
 ------------------------------
         Mat   Eng   Sci  Chem   Mat   Eng   Sci  Chem   Mat   Eng   Sci  Chem
Ravi    40.0  56.0  34.0  45.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Syam    67.0  87.0  56.0  67.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Rafad   55.0  34.0  78.0  89.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Abhi    45.0  56.0  89.0  89.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Shaan    NaN   NaN   NaN   NaN  50.0  66.0  81.0  56.0   NaN   NaN   NaN   NaN
Mahi     NaN   NaN   NaN   NaN  77.0  87.0  87.0  79.0   NaN   NaN   NaN   NaN
Viru     NaN   NaN   NaN   NaN  97.0  34.0  69.0  12.0   NaN   NaN   NaN   NaN
Mona     NaN   NaN   NaN   NaN  69.0  66.0  71.0  34.0   NaN   NaN   NaN   NaN
Astha    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  67.0  56.0  56.0  34.0
Rohit    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  89.0  87.0  67.0  56.0
Rahul    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  98.0  89.0  56.0  

In [50]:
df_concat2.fillna(value=0,inplace=True)
df_concat2

Mat   Eng   Sci  Chem   Mat   Eng   Sci  Chem   Mat   Eng   Sci  Chem
Ravi    40.0  56.0  34.0  45.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Syam    67.0  87.0  56.0  67.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Rafad   55.0  34.0  78.0  89.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Abhi    45.0  56.0  89.0  89.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
Shaan    0.0   0.0   0.0   0.0  50.0  66.0  81.0  56.0   0.0   0.0   0.0   0.0
Mahi     0.0   0.0   0.0   0.0  77.0  87.0  87.0  79.0   0.0   0.0   0.0   0.0
Viru     0.0   0.0   0.0   0.0  97.0  34.0  69.0  12.0   0.0   0.0   0.0   0.0
Mona     0.0   0.0   0.0   0.0  69.0  66.0  71.0  34.0   0.0   0.0   0.0   0.0
Astha    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  67.0  56.0  56.0  34.0
Rohit    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  89.0  87.0  67.0  56.0
Rahul    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  98.0  89.0  56.0  56.0
Shital   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  56.0  71.0  87.0  87.0

#  Merge

In [59]:
df1=pd.DataFrame(data={'Key':['k0','k1','k2','k3'],
                      'Eng':[56,87,34,56],
                      'Sci':[34,56,78,89],
                      'Chem':[45,67,89,89]})


df2=pd.DataFrame(data={'Key':['k0','k1','k2','k3'],
                      'Eng':[6,7,4,6],
                      'Sci':[4,6,8,9],
                      'Chem':[5,7,9,9]})


df3=pd.DataFrame(data={'Key':['k0','k1','k2','k3'],
                      'Eng':[56,87,34,56],
                      'Sci':[34,56,78,89],
                      'Chem':[45,67,89,89]})

df1

Key  Eng  Sci  Chem
0  k0   56   34    45
1  k1   87   56    67
2  k2   34   78    89
3  k3   56   89    89

In [63]:
merg1=pd.merge(df1,df2,on='Key')
merg1

Key  Eng_x  Sci_x  Chem_x  Eng_y  Sci_y  Chem_y
0  k0     56     34      45      6      4       5
1  k1     87     56      67      7      6       7
2  k2     34     78      89      4      8       9
3  k3     56     89      89      6      9       9

In [67]:
left=pd.DataFrame(data={'A':['A1','A2','A3','A4'],
                       'B':['B1','B2','B3','B4']},index=['S1','S2','S3','S4'])
right=pd.DataFrame(data={'C':['C1','C2','C3','C4'],
                        'D':['D1','D2','D3','D4']},index=['S0','S1','S2','S3'])

left.join(right,how='inner')

A   B   C   D
S1  A1  B1  C2  D2
S2  A2  B2  C3  D3
S3  A3  B3  C4  D4

In [68]:
left.join(right,how='outer')

A    B    C    D
S0  NaN  NaN   C1   D1
S1   A1   B1   C2   D2
S2   A2   B2   C3   D3
S3   A3   B3   C4   D4
S4   A4   B4  NaN  NaN

# Data Manipulation

In [69]:
import pandas as pd
import numpy as np

df=pd.read_csv('titanic_train.csv')
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

#### Check unique values

In [70]:
#similarly you can check any column unique value

df['Survived'].unique()

array([0, 1], dtype=int64)

### Rename Categories

In [72]:
# How to rename
new_survived=pd.Categorical(df['Survived'])
new_survived=new_survived.rename_categories(['Dead','Survived'])

new_survived.describe()

counts     freqs
categories                  
Dead           549  0.616162
Survived       342  0.383838

In [74]:
df['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [75]:
new_Pclass=pd.Categorical(df['Pclass'],ordered=True)
new_Pclass=new_Pclass.rename_categories(['Class 1','Class2','Class3'])
new_Pclass.describe()

counts     freqs
categories                  
Class 1        216  0.242424
Class2         184  0.206510
Class3         491  0.551066

### Saved Survived, Pclass to DataFrame

In [81]:
#saving to data frame
df['Survived']=new_survived

In [82]:
# saving to data Frame
df['Pclass']=new_Pclass

In [83]:
df.head()

PassengerId  Survived   Pclass  \
0            1      Dead   Class3   
1            2  Survived  Class 1   
2            3  Survived   Class3   
3            4  Survived  Class 1   
4            5      Dead   Class3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [84]:
# Cabin.unique
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [88]:
# convert data to str
char_cabin=df['Cabin'].astype(str) 

# List Comprehension
char_cabin=np.array([cabin[0] for cabin in char_cabin])

# Take first Letter
char_cabin=pd.Categorical(char_cabin)
char_cabin.describe()

counts     freqs
categories                  
A               15  0.016835
B               47  0.052750
C               59  0.066218
D               33  0.037037
E               32  0.035915
F               13  0.014590
G                4  0.004489
T                1  0.001122
n              687  0.771044

In [89]:
df['Cabin']=char_cabin

In [90]:
df.head(5)

PassengerId  Survived   Pclass  \
0            1      Dead   Class3   
1            2  Survived  Class 1   
2            3  Survived   Class3   
3            4  Survived  Class 1   
4            5      Dead   Class3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500     n        S  
1      0          PC 17599  71.2833     C        C  
2      0  STON/O2. 3101282   7.9250     n        S  
3      0            113803  53.1000     C        S  
4      0            373450   8.0500     n        S

### Find all the Passenger who's age is Missing

In [98]:
missing=np.where(df['Age'].isnull()==True)
# will show index
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [99]:
df.loc[missing].head()

PassengerId  Survived  Pclass                           Name     Sex  Age  \
5             6      Dead  Class3               Moran, Mr. James    male  NaN   
17           18  Survived  Class2   Williams, Mr. Charles Eugene    male  NaN   
19           20  Survived  Class3        Masselmani, Mrs. Fatima  female  NaN   
26           27      Dead  Class3        Emir, Mr. Farred Chehab    male  NaN   
28           29  Survived  Class3  O'Dwyer, Miss. Ellen "Nellie"  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
5       0      0  330877   8.4583     n        Q  
17      0      0  244373  13.0000     n        S  
19      0      0    2649   7.2250     n        C  
26      0      0    2631   7.2250     n        C  
28      0      0  330959   7.8792     n        Q

### Find the maximum Fare

In [100]:
index=np.where(df['Fare']==max(df['Fare']))
index

(array([258, 679, 737], dtype=int64),)

In [101]:
df.loc[index]

PassengerId  Survived   Pclass                                Name  \
258          259  Survived  Class 1                    Ward, Miss. Anna   
679          680  Survived  Class 1  Cardeza, Mr. Thomas Drake Martinez   
737          738  Survived  Class 1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292     n        C  
679    male  36.0      0      1  PC 17755  512.3292     B        C  
737    male  35.0      0      0  PC 17755  512.3292     B        C

### Find the family who has has highest Members?

In [105]:
# new family column created
df['Family']=df['SibSp']+df['Parch']

most_family=np.where(df['Family']==max(df['Family']))
df.loc[most_family]

PassengerId Survived  Pclass                               Name     Sex  \
159          160     Dead  Class3         Sage, Master. Thomas Henry    male   
180          181     Dead  Class3       Sage, Miss. Constance Gladys  female   
201          202     Dead  Class3                Sage, Mr. Frederick    male   
324          325     Dead  Class3           Sage, Mr. George John Jr    male   
792          793     Dead  Class3            Sage, Miss. Stella Anna  female   
846          847     Dead  Class3           Sage, Mr. Douglas Bullen    male   
863          864     Dead  Class3  Sage, Miss. Dorothy Edith "Dolly"  female   

     Age  SibSp  Parch    Ticket   Fare Cabin Embarked  Family  
159  NaN      8      2  CA. 2343  69.55     n        S      10  
180  NaN      8      2  CA. 2343  69.55     n        S      10  
201  NaN      8      2  CA. 2343  69.55     n        S      10  
324  NaN      8      2  CA. 2343  69.55     n        S      10  
792  NaN      8      2  CA. 2343  69.55     n        S      10  
846  NaN      8      2  CA. 2343  69.55     n        S      10  
863  NaN      8      2  CA. 2343  69.55     n        S      10

In [106]:
df=pd.read_csv('hrdata.csv')

In [107]:
df

Name  HireDate   Salary  SickDaysremaining
0  Graham Chapman  03/15/14  50000.0                 10
1     John Cleese  06/01/15  65000.0                  8
2       Eric Idle  05/12/14  45000.0                 10
3     Terry Jones  11/01/13  70000.0                  3
4   Terry Gilliam  08/12/14  48000.0                  7
5   Michael Palin  05/23/13  66000.0                  8

In [110]:
df['HireDate'].dtype

dtype('O')

In [112]:
print(type(df['HireDate'][0])) # 0 is zeroth rows

<class 'str'>


In [113]:
df=pd.read_csv('hrdata.csv',index_col='Name',parse_dates=['HireDate'])
print(df)

                 HireDate   Salary  SickDaysremaining
Name                                                 
Graham Chapman 2014-03-15  50000.0                 10
John Cleese    2015-06-01  65000.0                  8
Eric Idle      2014-05-12  45000.0                 10
Terry Jones    2013-11-01  70000.0                  3
Terry Gilliam  2014-08-12  48000.0                  7
Michael Palin  2013-05-23  66000.0                  8


In [114]:
print(type(df['HireDate'][0]))
print(type(df['HireDate'][1]))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
