# NUMPY-- Numerical Python

"Numpy is a Python package, It stands for Numerical Python,It consist of numerical pythons"

In [4]:
# calling numpy Library

import numpy

In [5]:
# array is a continues memory location [1],[2],[3],[4],[5]

numpy.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
# array is a continues memory location [11],[12],[13],[14],[15]

numpy.array([11,12,13,14,15])

array([11, 12, 13, 14, 15])

In [6]:
a=numpy.array([11,12,14,15,18])


In [7]:
a

array([11, 12, 14, 15, 18])

In [8]:
b=numpy.array([90,30,40,89,2,15])

In [9]:
b

array([90, 30, 40, 89,  2, 15])

In [10]:
import numpy as np

In [12]:
a=np.array([1,12,13,115,199])

In [14]:
a

array([  1,  12,  13, 115, 199])

In [15]:
b=np.array([13,16,76,98])

b

array([13, 16, 76, 98])

In [16]:
# a.size will tell us the size of elements in (a)

a.size

5

In [22]:
#checking elements in b

b.size

4

In [23]:
# checking shape of a

print(a.shape)

"showing a 1 dimension data or a vector data"


(5,)


'showing a 1 dimension data or a vector data'

In [25]:
print(b.shape)

"b.shape is showing 1 dimension data or a vector data "

(4,)


'b.shape is showing 1 dimension data or a vector data '

# WORKING WITH 2 DIMENSION DATA 

In [26]:
#CREATING TWO DIMENSION DATA 

# C= NP.ARRAY([ROW1[COLUMN1,COLUMN2],ROW2[COLOUMN1,COLOUMN2]])

C=np.array([[1,2],[3,4]])


In [27]:
C

array([[1, 2],
       [3, 4]])

In [30]:
print(C.shape)

"Here C.shape showing us 2 dimension data"

(2, 2)


'Here C.shape showing us 2 dimension data'

In [33]:
d=np.array([[3,6],[19,91]])

In [34]:
print(d.shape,"dimension")
print(d.size,"size")

(2, 2) dimension
4 size


In [6]:
f=np.array([[12,13,14],[15,16,18]])
print(f.size,'size of the elements')
print(f.shape,'shape of the data')

6 size of the elements
(2, 3) shape of the data


In [8]:
fi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
fi

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
fi.size

16

In [11]:
fi.shape

(4, 4)

In [16]:
h=np.array([[1,2,3],[4,5,6],[7,8,9]])
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
h.size

9

In [18]:
h.shape

(3, 3)

RE-SHAPE METHORD

In [20]:
# we can re-shape the content,if it is [4rows,3column]then we change it[3rows,4column]

In [21]:
o=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
o

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
# checking the size

o.size

12

In [23]:
# checking the shape

o.shape

(4, 3)

In [26]:
# changing the size of the variable o, now the elements are in 3row,4column
o.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
# changing the size of the variable o, now the elements are in 2rows, 6 column

o.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
# finding maximum from o by maximum function

o.max()

12

In [29]:
# finding minimum from o by minimum function

o.min()

1

In [30]:
# finding data type from o variable by dtype 

o.dtype

dtype('int32')

In [31]:
# this says that one elements contains 4 bytes

o.itemsize

4

In [32]:
o.size

12

In [33]:
# to check which memory location it is 

o.data

# ARANGE FUNCTION

In [34]:
o=np.arange(6)

In [35]:
o

array([0, 1, 2, 3, 4, 5])

In [38]:
op=np.arange(10)

In [39]:
op

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# reshape o into 2rows and 3 columns

a=o.reshape(2,3)

In [42]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
x=np.arange(15)

In [44]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
# making new variable output from x and breaking x into 3 rows 5 columns

output=x.reshape(3,5)

In [46]:
#checking output of output

output

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
output.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [55]:
a=np.arange(21)

In [50]:
e=a.reshape(3,7)

In [56]:
e

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [59]:
a=np.array([[1,2],[3,4],[5,6]],dtype='float64')

In [60]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [61]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [62]:
# checking data type of a

a.dtype

dtype('float64')

In [63]:
# checking dimension()
a.shape

(3, 2)

In [64]:
# checking size
a.size

6

In [65]:
# checking bytes consumed by per elements in variable a 
a.itemsize

8

In [66]:
#will update the dimension of the file(01 is rows, 2nd is columns)
a.ndim

2

In [67]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [68]:
#  a.shape wil tell us the size of the table

a.shape

(3, 2)

In [72]:
x=np.arange((25),dtype="float64")

In [73]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [74]:
x1=x.reshape(5,5)

In [75]:
x1

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [76]:
# checking data type of new variable x1

x1.dtype

dtype('float64')

In [77]:
# checking bytes consumed by per elements

x1.itemsize

8

In [78]:
# checking the size of the all ements inside x1

x1.size

25

In [79]:
# checking the dimension of the x1

x1.ndim

2

In [80]:
# checking the shape of the variable in x1

print(x1.shape)

(5, 5)


In [81]:
a=np.arange((12),dtype='int32').reshape(4,3)

In [82]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [84]:
a.dtype

dtype('int32')

In [85]:
a.size

12

In [86]:
a.shape

(4, 3)

In [87]:
a.itemsize

4

In [88]:
a.ndim

2

# RAVEL FUNCTION

In [89]:
# ravel operation where you can convert one numpy array into a single row

print(a.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [90]:
import numpy as np

b=np.array([[1.5,2.3,6.7],[8.9,6,0]],dtype='int32')

In [91]:
b

array([[1, 2, 6],
       [8, 6, 0]])

In [92]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [94]:
# ARANGE FUNCTION

np.arange(5)

array([0, 1, 2, 3, 4])

In [95]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
#(start---->stop------>jump or loop)

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [97]:
# start no 10, end no 30, jump of 5

np.arange(10,30,5)

array([10, 15, 20, 25])

In [98]:
b=np.arange(25).reshape(5,5)

In [99]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# BROADCASTING IN NUMPY:

In [100]:
""" BROADCASTING IN NUMPY
The term broadcasting describes how numpy treats arrays with arthmetic operation. subject to certain constraints, the smaller 
array is "broadcast" across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing 
array operations
"""

' BROADCASTING IN NUMPY\nThe term broadcasting describes how numpy treats arrays with arthmetic operation. \nsubject to certain constraints, the smaller array is "broadcast"across the larger\narray so that they have compatible shapes.Broadcasting provides a means of vectorizing \narray operations\n'

In [102]:
a=np.array([1.0,2.0,3.0])
b=np.array([2.0,2.0,2.0])
a*b

array([2., 4., 6.])

In [103]:
a=np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])

In [104]:
a=np.array([1.0,2.0,3.0])
b=np.array(2.0)
a*b

array([2., 4., 6.])

In [107]:
a=np.array([10,20,30,40,50])
b=np.arange(5)
print(a,"values of a")
print(b,"values of b")

[10 20 30 40 50] values of a
[0 1 2 3 4] values of b


In [108]:
a*b

array([  0,  20,  60, 120, 200])

In [109]:
a+b

array([10, 21, 32, 43, 54])

In [110]:
a-b

array([10, 19, 28, 37, 46])

In [111]:
b**2

array([ 0,  1,  4,  9, 16], dtype=int32)

Random Function

In [112]:
b=np.random.randn(4,3)

In [113]:
b

array([[-0.45600079,  0.81048735, -0.1493198 ],
       [ 1.02313727,  1.44910874,  0.75990424],
       [-0.4490374 , -0.71791139,  0.13764583],
       [ 1.30687253, -0.93242516, -0.44047803]])

In [116]:
c=np.ones([4,3])

In [117]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [118]:
b+c

array([[0.54399921, 1.81048735, 0.8506802 ],
       [2.02313727, 2.44910874, 1.75990424],
       [0.5509626 , 0.28208861, 1.13764583],
       [2.30687253, 0.06757484, 0.55952197]])

# UNIVERSAL FUNCTIONS

In [119]:
B=np.arange(3)

In [120]:
B

array([0, 1, 2])

In [121]:
# finding exponent of the data
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [122]:
# finding the sq root of the data

np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [123]:
c=np.array([2,1,4])
np.add(B,c)

array([2, 2, 6])

# INDEXING,SLICING AND ITERATING

In [124]:
a=np.arange(10)

In [125]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
a[2]

2

In [127]:
print(a[9])

9


In [128]:
a[9]

9

In [129]:
a[-5]

5

In [131]:
a[-8:-5]

array([2, 3, 4])

In [132]:
d2=np.arange(20)

In [133]:
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [134]:
d2[11:15]

array([11, 12, 13, 14])

In [1]:
import numpy as np

In [2]:
d3=np.array([np.nan,1,2,3,np.nan,6,7,8])

In [3]:
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

the random module provides nice functions to generate random numbers(and also statistical distributions) of any given shape.rand function will generate any number between 0 to 1

In [4]:
np.random.rand(2,2)

array([[0.22612377, 0.14704058],
       [0.15888992, 0.29999561]])

Randn will generate any number for normal distribution in the given dimension format

In [5]:
np.random.randn(2,3)

array([[-0.70423887, -0.28992673,  1.05459536],
       [-1.13593541,  0.44568755,  0.35852454]])

# Done with Numpy